export const pricingTiers = {
	free: {
		name: "Free",
		max_upload_analyze: 3,
		max_outfit_plans_per_month: 5,
		max_wardrobe_items: 10,
		agent_calls_minutes: 0,
		calendar_integration: true,
		ai_styling_advice: true,
		weather_integration: false,
		outfit_alternatives: true,
		monthly_style_reports: false,
		priority_support: false,
		price_monthly: 0,
	},
	spotlight: {
		name: "Spotlight",
		max_upload_analyze: 20,
		max_outfit_plans_per_month: 10,
		max_wardrobe_items: 30,
		agent_calls_minutes: 5,
		calendar_integration: true,
		ai_styling_advice: true,
		weather_integration: false,
		outfit_alternatives: true,
		monthly_style_reports: true,
		priority_support: false,
		price_monthly: 9.99,
	},
	elite: {
		name: "Elite",
		max_upload_analyze: 50,
		max_outfit_plans_per_month: 20,
		max_wardrobe_items: 60,
		agent_calls_minutes: 15,
		calendar_integration: true,
		ai_styling_advice: true,
		weather_integration: true,
		outfit_alternatives: true,
		monthly_style_reports: true,
		priority_support: false,
		price_monthly: 19.99,
	},
	icon: {
		name: "Icon",
		max_upload_analyze: 100,
		max_outfit_plans_per_month: 50,
		max_wardrobe_items: 150,
		agent_calls_minutes: 30,
		calendar_integration: true,
		ai_styling_advice: true,
		weather_integration: true,
		outfit_alternatives: true,
		monthly_style_reports: true,
		priority_support: true,
		price_monthly: 39.99,
	},
};
