export const pricingTiers = {
	free: {
		name: "Free",
		max_upload_analyze: 1,
		max_outfit_plans_per_month: 5,
		max_wardrobe_items: 10,
		ai_calls_per_day: 1,
		calendar_integration: false,
		ai_styling_advice: false,
		voice_integration: false,
		weather_integration: false,
		outfit_alternatives: false,
		monthly_style_reports: false,
		priority_support: false,
		price_monthly: 0,
	},
	spotlight: {
		name: "Spotlight",
		max_upload_analyze: 5,
		max_outfit_plans_per_month: 30,
		max_wardrobe_items: 30,
		ai_calls_per_day: 10,
		calendar_integration: true,
		voice_integration: false,
		ai_styling_advice: true,
		weather_integration: false,
		outfit_alternatives: true,
		monthly_style_reports: false,
		priority_support: false,
		price_monthly: 9.99,
	},
	elite: {
		name: "Elite",
		max_upload_analyze: 100,
		max_outfit_plans_per_month: 100,
		max_wardrobe_items: 50,
		ai_calls_per_day: 50,
		calendar_integration: true,
		ai_styling_advice: true,
		voice_integration: false,
		weather_integration: true,
		outfit_alternatives: true,
		monthly_style_reports: true,
		priority_support: false,
		price_monthly: 19.99,
	},
	icon: {
		name: "Icon",
		max_upload_analyze: 300,
		max_outfit_plans_per_month: 300,
		max_wardrobe_items: 300,
		ai_calls_per_day: 200,
		calendar_integration: true,
		ai_styling_advice: true,
		voice_integration: true,
		weather_integration: true,
		outfit_alternatives: true,
		monthly_style_reports: true,
		priority_support: true,
		price_monthly: 39.99,
	},
};
